### ISSUE TITLE
Some problems in the plug-in installation

### ISSUE THREAD

**Issue by yuanyimei** [gperonato/GHCitySim#4]
Hi@Aymeric Delmas
Thank you very much for these amazing components,this has changed the game for sure.But the honeybee0.0.59 is no longer available on food4rhino.Can you send me a copy of the honeybee0.0.59?My e-mail address yuanymarch@163.com .Thank you again. Hoping to hear from you.

**Comment by gperonato** [comment]
Hi Yanyimei,
you can find the legacy components here:
https://github.com/mostaphaRoudsari/honeybee/releases/tag/Ver.0.0.59

The ones you need to run GhCitySim are also included in the sample Grasshopper file provided here in the repository.

Giuseppe
