### ISSUE TITLE
Invalid climate file produced by EPW-to-Cli

### ISSUE THREAD

**Issue by JulienDespax** [gperonato/GHCitySim#6]
Hi @gperonato !
I've been working with your GHCitySim components (thx for the great work!). I encountered a problem when trying to run the LoadResults component : the component can't find the SW.out file, because there is no such file in my directory.
So maybe the problem comes from the RunSimulation component? Note that the RunSimulation component is able to write the XML files (I find them in my directory and can open them in CitySim).

Thank you!

![image](https://user-images.githubusercontent.com/48280993/53877463-80206200-4009-11e9-8480-53f0e919c99b.png)

**Comment by gperonato** [comment]
Hi Julien,
Were you able to run the simulation with the RunSimulation component? In that case, you should find various *.out files in your simulation directory including the one that the LoadResults component is not able to find.
Let me know.
Giuseppe

**Comment by JulienDespax** [comment]
Hello Giuseppe,

thx for your quick answer. You were right, the RunSimulation wasn't able to perform the simulation (see pic below) since there was no climate file to be found. So maybe the EPW-to-Clim component was the problem. Anyway I defined the path to the cli file manually, so the simulation works fine now :)

Note that I was using the previous version of GHCitySim (the one that runs HB 0.0.59). I just saw that you uploaded a new version recently, glad to see the work goes on, I'll update right away!

Julien

![image](https://user-images.githubusercontent.com/48280993/53952023-1323cf80-40d0-11e9-9a7d-f2920fd5931e.png)

![image](https://user-images.githubusercontent.com/48280993/53952260-9a714300-40d0-11e9-8f85-0452fb83d7fd.png)

**Comment by gperonato** [comment]
Hi Julien,

It seems indeed that there are some problems with the conversion of the weather file.
If you send me your "*.epw", I can have a look at it. My email is giuseppe.peronato[at]angstrom.uu.se

Yes, I have updated yesterday the components. If you can test them and give me some feedback,  I would much appreciate it!

Best,

Giuseppe

**Comment by JulienDespax** [comment]
Thx Guiseppe, I'll send you my epw. I'll let you know how I'm doing with the new version :)
Julien

**Comment by gperonato** [comment]
There was a problem with the file naming. I updated the component, it should work now. Let me know, Giuseppe

**Comment by JulienDespax** [comment]
The new component works fine! Thank you!

**Comment by rajendra6927989** [comment]
Hello, 
I need to change .epw weather file into .cli citysim weather file. Could you please help me to do that?

**Comment by gperonato** [comment]
> Hello,
> I need to change .epw weather file into .cli citysim weather file. Could you please help me to do that?

Hi @rajendra6927989, did you try using the component?

In case it might help, here is a reference for cli files:
https://github.com/kaemco/CitySim-Solver/wiki/The-Climate-File
